# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-20 11:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='foodmaterial',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='foodmaterial',
            unique_together=set([('material', 'food_recipe')]),
        ),
        migrations.AlterUniqueTogether(
            name='foodnutrition',
            unique_together=set([('nutrition', 'foodrecipe')]),
        ),
    ]
