# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-27 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('id_ctma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.FoodRecipe')),
            ],
            options={
                'db_table': 'kitchenrock_dinhduong_monan',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=100)),
            ],
            options={
                'db_table': 'kitchenrock_dinhduong',
            },
        ),
        migrations.AddField(
            model_name='foodnutrition',
            name='id_dd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.Nutrition'),
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='dinhduong',
            field=models.ManyToManyField(through='kitchenrock_api.FoodNutrition', to='kitchenrock_api.Nutrition'),
        ),
    ]
