# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-27 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0002_auto_20170927_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathological',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='ten', max_length=200)),
                ('question', models.TextField(db_column='cauhoi')),
            ],
            options={
                'db_table': 'kitchenrock_benhly',
            },
        ),
        migrations.CreateModel(
            name='SearchPathological',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.IntegerField(default=0)),
                ('min_value', models.IntegerField(default=0)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.Nutrition')),
                ('pathological', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.Pathological')),
            ],
            options={
                'db_table': 'kitchenrock_tracuu_benhly',
            },
        ),
        migrations.AddField(
            model_name='pathological',
            name='nutrition',
            field=models.ManyToManyField(through='kitchenrock_api.SearchPathological', to='kitchenrock_api.Nutrition'),
        ),
        migrations.AddField(
            model_name='user',
            name='pathological',
            field=models.ManyToManyField(db_table='kitchenrock_benhly_nguoidung', to='kitchenrock_api.Pathological'),
        ),
    ]
