# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-20 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0002_auto_20171020_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmaterial',
            name='value',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='foodnutrition',
            name='value',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
