# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-28 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0003_auto_20170927_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodnutrition',
            old_name='id_ctma',
            new_name='ctma',
        ),
        migrations.RenameField(
            model_name='foodnutrition',
            old_name='id_dd',
            new_name='dinhduong',
        ),
    ]
