# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-25 14:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchenrock_api', '0004_auto_20171025_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialNutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.Material')),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchenrock_api.Nutrition')),
            ],
            options={
                'db_table': 'kitchenrock_material_nutritions',
            },
        ),
        migrations.AlterField(
            model_name='foodmaterial',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AlterField(
            model_name='foodnutrition',
            name='value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='material',
            name='nutritions',
            field=models.ManyToManyField(through='kitchenrock_api.MaterialNutrition', to='kitchenrock_api.Nutrition'),
        ),
        migrations.AlterUniqueTogether(
            name='materialnutrition',
            unique_together=set([('nutrition', 'material')]),
        ),
    ]
