"""
Django settings for kitchenrock project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from os.path import dirname
from os.path import join

from . import env
from . import BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG404 = True
STATICFILES_DIRS = [join(BASE_DIR, '')]
MEDIA_ROOT = join(BASE_DIR, 'media')
GEOIP_PATH = join(BASE_DIR, 'geo')
DOC_URL = '/docs/'
DOC_ROOT = join(BASE_DIR, 'docs')
ALLOWED_HOSTS = []

USER_PHOTOS_SYNC_PATH = 'uphotos'
USER_DATA_SYNC_PATH = 'updata'

# SECURITY WARNING: keep the secret key used in production secret!
# Raises ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')
CSRF_COOKIE_SECURE = True
ELASTIC_HOST = env('ELASTIC_HOST')
ELASTIC_PORT = env('ELASTIC_PORT')
API_HOST = env('API_HOST')
API_PORT = env('API_PORT')
MEDIA_URL = "/media/"
PUBLIC_BASE = env('PUBLIC_BASE')

# Application definition
KITCHENROCK_API = 'kitchenrock_api'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'kitchenrock_api',
    'template_email',
]

MIDDLEWARE_CLASSES = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kitchenrock.dbrouter.DbRouterMiddleware',
    'kitchenrock_api.middleware.ApiMiddleware',
)

ROOT_URLCONF = 'kitchenrock.urls'

# Use Django templates using the new Django 1.8 TEMPLATES settings
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR, 'templates'),
            # insert more TEMPLATE_DIRS here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # Insert your TEMPLATE_CONTEXT_PROCESSORS here or use this
                # list if you haven't customized them:
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                # 'django.template.context_processors.i18n',
                # 'django.template.context_processors.media',
                # 'django.template.context_processors.tz',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'kitchenrock_api.authentications.KeyPinBackend',
]

ROOT_URLCONF = 'kitchenrock.urls'

WSGI_APPLICATION = 'kitchenrock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':  env('DB_NAME'),#'db_shinobi',
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASS',default=''),
        'HOST': env('DB_HOST'),   # Or an IP Address that your DB is hosted on
        'PORT': env('DB_PORT'),
    },
}

DATABASE_ROUTERS = ('kitchenrock.dbrouter.DatabaseRouter',)

# Log everything to the logs directory at the top
LOGFILE_ROOT = join(dirname(BASE_DIR), 'logs')

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
]

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'kitchenrock_api.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'kitchenrock_api.authentications.TokenAuthentication'
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'EXPIRED_FOREVER': '2000-10-10 00:00:00'
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.sendgrid.net')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='vms_mailer')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='vmsmailer1')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SENDGRID_API_KEY = env('SENDGRID_API_KEY',default='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')


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SUPPORT_EMAIL = env('SUPPORT_EMAIL', default='support@kitchenrock.com')
BCC_EMAIL_ADDRESS = env('BCC_EMAIL_ADDRESS', default='support@kitchenrock.com')
ALLOWED_EMAILS = env('ALLOWED_EMAILS', default='*')
SUPPORT_PHONE = env('SUPPORT_PHONE', default='xxx-xxx-xxxx')

# Authentication Settings
AUTH_USER_MODEL = 'kitchenrock_api.User'  # 'authtools.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'
STATIC_DIR = 'static'
STATICFILES_DIRS = [join(BASE_DIR, STATIC_DIR)]


